### ISSUE TITLE
feat: 스토리북 컴포넌트 세팅을 한다

### ISSUE THREAD

**Issue by rainleee** [rainleee/poke#45]
## (기획) 기획안, 기능 정의서 관련 링크 추가 (issue, notion 등)
- [](url)

## Todo
- [ ] 사용 색상 스토리북 표현
- [ ] 사용 컴포넌트 스토리북 모듈화
- [ ] 인터렉션 스토리북 테스트코드 작성
